# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1836b6fc7d2c08fd814f99a16984825"
name = "Luudhealth Consultation"
application_url = "https://consultation.luudhealth.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "iplaysafe-consultancy-app-store.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_draft_orders,read_orders,write_orders,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://consultation.luudhealth.com/auth/callback",
  "https://consultation.luudhealth.com/auth/shopify/callback",
  "https://consultation.luudhealth.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://consultation.luudhealth.com"
subpath = "tip"
prefix = "apps"

[pos]
embedded = false
